import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Serene Peach Anarkali',
    description: 'A beautiful Anarkali suit in a serene peach shade, perfect for festive occasions. Features delicate embroidery and a flowing silhouette.',
    price: 4999,
    images: ['https://picsum.photos/id/102/800/1200', 'https://picsum.photos/id/103/800/1200', 'https://picsum.photos/id/104/800/1200'],
    category: 'suits',
    sizes: ['S', 'M', 'L', 'XL'],
    fabric: 'Georgette',
    code: 'NK001',
    creationDate: new Date('2024-07-20T10:00:00Z').toISOString(),
    bestseller: true,
  },
  {
    id: '2',
    name: 'Royal Blue Banarasi Saree',
    description: 'A timeless Banarasi saree in a rich royal blue, featuring intricate gold zari work. A masterpiece of traditional weaving.',
    price: 8999,
    images: ['https://picsum.photos/id/201/800/1200', 'https://picsum.photos/id/202/800/1200', 'https://picsum.photos/id/203/800/1200'],
    category: 'sarees',
    sizes: ['Free Size'],
    fabric: 'Silk',
    code: 'NK002',
    creationDate: new Date('2024-07-15T11:30:00Z').toISOString(),
    bestseller: true,
  },
  {
    id: '3',
    name: 'Pastel Green Kurti',
    description: 'A chic and comfortable kurti in a lovely pastel green. Ideal for casual outings and office wear.',
    price: 1899,
    images: ['https://picsum.photos/id/301/800/1200', 'https://picsum.photos/id/302/800/1200'],
    category: 'kurtis',
    sizes: ['M', 'L', 'XL'],
    fabric: 'Cotton',
    code: 'NK003',
    creationDate: new Date('2024-06-25T09:00:00Z').toISOString(),
    bestseller: false,
  },
  {
    id: '4',
    name: 'Bohemian Floral Dress',
    description: 'A breezy and beautiful bohemian style dress with a vibrant floral print. Perfect for a summer day out.',
    price: 2799,
    images: ['https://picsum.photos/id/401/800/1200', 'https://picsum.photos/id/402/800/1200', 'https://picsum.photos/id/403/800/1200'],
    category: 'dresses',
    sizes: ['S', 'M', 'L'],
    fabric: 'Rayon',
    code: 'NK004',
    creationDate: new Date('2024-07-01T14:00:00Z').toISOString(),
    bestseller: true,
  },
  {
    id: '5',
    name: 'Classic Red Silk Saree',
    description: 'An elegant red silk saree with a simple gold border. A must-have for every ethnic wardrobe.',
    price: 6500,
    images: ['https://picsum.photos/id/211/800/1200', 'https://picsum.photos/id/212/800/1200'],
    category: 'sarees',
    sizes: ['Free Size'],
    fabric: 'Art Silk',
    code: 'NK005',
    creationDate: new Date('2024-05-10T10:00:00Z').toISOString(),
    bestseller: false,
  },
  {
    id: '6',
    name: 'Midnight Black Sharara Suit',
    description: 'A stunning sharara suit in midnight black with silver sequin work. Perfect for evening parties.',
    price: 5599,
    images: ['https://picsum.photos/id/111/800/1200', 'https://picsum.photos/id/112/800/1200', 'https://picsum.photos/id/113/800/1200'],
    category: 'suits',
    sizes: ['M', 'L', 'XL'],
    fabric: 'Velvet',
    code: 'NK006',
    creationDate: new Date('2024-07-22T18:00:00Z').toISOString(),
    bestseller: true,
  },
  {
    id: '7',
    name: 'Ivory Chikankari Kurti',
    description: 'An exquisite ivory kurti featuring authentic Lucknowi Chikankari embroidery. A symbol of grace.',
    price: 3200,
    images: ['https://picsum.photos/id/311/800/1200', 'https://picsum.photos/id/312/800/1200'],
    category: 'kurtis',
    sizes: ['S', 'M', 'L'],
    fabric: 'Cotton Cambric',
    code: 'NK007',
    creationDate: new Date('2023-12-20T10:00:00Z').toISOString(),
    bestseller: false,
  },
  {
    id: '8',
    name: 'Crimson Sunset Gown',
    description: 'A breathtaking evening gown in shades of crimson and orange, mimicking a sunset. Features a flattering A-line cut.',
    price: 7500,
    images: ['https://picsum.photos/id/411/800/1200', 'https://picsum.photos/id/412/800/1200'],
    category: 'dresses',
    sizes: ['S', 'M', 'L', 'XL'],
    fabric: 'Satin',
    code: 'NK008',
    creationDate: new Date('2024-07-18T12:00:00Z').toISOString(),
    bestseller: false,
  },
  {
    id: '9',
    name: 'Emerald Green Kanjeevaram',
    description: 'A majestic Kanjeevaram saree in a deep emerald green, handwoven with pure mulberry silk and real zari.',
    price: 15999,
    images: ['https://picsum.photos/id/221/800/1200', 'https://picsum.photos/id/222/800/1200'],
    category: 'sarees',
    sizes: ['Free Size'],
    fabric: 'Kanjeevaram Silk',
    code: 'NK009',
    creationDate: new Date('2024-07-25T15:00:00Z').toISOString(),
    bestseller: false,
  },
  {
    id: '10',
    name: 'Mustard Yellow Palazzo Suit',
    description: 'A vibrant and trendy palazzo suit in mustard yellow, paired with a printed dupatta.',
    price: 4250,
    images: ['https://picsum.photos/id/121/800/1200', 'https://picsum.photos/id/122/800/1200'],
    category: 'suits',
    sizes: ['L', 'XL', 'XXL'],
    fabric: 'Crepe',
    code: 'NK010',
    creationDate: new Date('2024-07-05T10:00:00Z').toISOString(),
    bestseller: true,
  },
];
